/* Generated by            cobc 2.0.0 */
/* Generated from          test.cbl */
/* Generated at            Nov 25 2013 23:11:25 */
/* GNU Cobol build date    Nov 25 2013 23:08:50 */
/* GNU Cobol package date  Feb 11 2012 12:36:31 UTC */
/* Compile command         cobc -xg test.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Attributes */

static const cob_field_attr a_1 =	{0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   3,   0, 0x0001, NULL};


/* Constants */
static const cob_field c_1	= {3, (cob_u8_ptr)"foo", &a_2};
static const cob_field c_2	= {3, (cob_u8_ptr)"bar", &a_2};
static const cob_field c_3	= {13, (cob_u8_ptr)"call status: ", &a_2};


/* Strings */
static const char st_1[]	= "test.cbl";
static const char st_2[]	= "CALL";
static const char st_3[]	= "DISPLAY";
static const char st_4[]	= "GOBACK";

