/* Generated by            cobc 2.0.0 */
/* Generated from          test.cbl */
/* Generated at            Nov 25 2013 23:11:25 */
/* GNU Cobol build date    Nov 25 2013 23:08:50 */
/* GNU Cobol package date  Feb 11 2012 12:36:31 UTC */
/* Compile command         cobc -xg test.cbl */

/* Program local variables for 'TEST' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[3];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int       b_1;	/* RETURN-CODE */
static cob_u8_t  b_5[3] __attribute__((aligned));	/* CALL-STATUS */

/* End of data storage */


/* Fields */
static cob_field f_5	= {3, b_5, &a_3};	/* CALL-STATUS */

/* End of fields */

