/* Generated by            cobc 2.0.0 */
/* Generated from          test.cbl */
/* Generated at            Nov 25 2013 23:11:25 */
/* GNU Cobol build date    Nov 25 2013 23:08:50 */
/* GNU Cobol package date  Feb 11 2012 12:36:31 UTC */
/* Compile command         cobc -xg test.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"test.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Nov 25 2013 23:11:25"
#define  COB_MODULE_DATE		20131125
#define  COB_MODULE_TIME		231125

/* Global variables */
#include "test.c.h"

/* Function prototypes */

static int		TEST ();
static int		TEST_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (TEST ());
}

/* Functions */

/* PROGRAM-ID 'TEST' */

/* ENTRY 'TEST' */

static int
TEST ()
{
  return TEST_ (0);
}

static int
TEST_ (const int entry)
{
  /* Program local variables */
  #include "test.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Save number of call params */
  module->module_num_params = cob_glob_ptr->cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 9         : Entry     TEST                    : test.cbl */
  l_2:;

  /* Line: 9         : CALL               : test.cbl */
  cob_set_location (st_1, 9, NULL, NULL, st_2);
  {
    cob_content	content_1;
    cob_field	content_fb_1 = { 4, content_1.data, &a_1 };

    content_1.dataint = 14;
    cob_procedure_params[0] = &content_fb_1;
    cob_procedure_params[1] = (cob_field *)&c_1;
    cob_procedure_params[2] = (cob_field *)&c_2;
    cob_glob_ptr->cob_call_params = 3;
    b_1 = cob_sys_xml (content_1.data, (cob_u8_ptr)"foo", (cob_u8_ptr)"bar");
    cob_set_int (&f_5, b_1);
  }

  /* Line: 16        : DISPLAY            : test.cbl */
  cob_set_location (st_1, 16, NULL, NULL, st_3);
  cob_display (0, 1, 2, &c_3, &f_5);

  /* Line: 17        : GOBACK             : test.cbl */
  cob_set_location (st_1, 17, NULL, NULL, st_4);
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "TEST";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())TEST;
  module->module_cancel.funcptr = (void *(*)())TEST_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_5, 48, 3);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'TEST' */

/* End functions */

